spring:
    application:
        name: iot-vmp-vmanager
        # 影子数据存储方式，支持redis、jdbc
        database: redis
        # 通信方式，支持kafka、http
        communicate: http
    redis:
        # Redis服务器IP
        host: 192.168.1.141
        #端口号
        port: 6379
        database: 6
        #访问密码,若你的redis服务器没有设置密码，就不需要用密码去连接
        password: 4767cb971b40a1300fa09b7f87b09d1c
        #超时时间
        timeout: 10000
    datasource: 
        name: eiot
        url: jdbc:mysql://192.168.1.141:3306/eiot?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=true
        username:
        password:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
server:
    port: 18080
sip:
    ip: 192.168.1.20
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    domain: 3402000000
    id: 34020000002000000001
    # 默认设备认证密码，后续扩展使用设备单独密码
    password: 12345678

auth: #32位小写md5加密（默认密码为admin）
    username: admin
    password: 21232f297a57a5a743894a0e4a801fc3

media: #zlm服务器的ip与http端口, 重点: 这是http端口
    ip: 192.168.1.20
    port: 9080
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    streamNoneReaderDelayMS:  1800000  # 无人观看多久关闭流

